
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"E:\OneDrive\OneDrive - The Chinese University of Hong Kong\CUHK\year4_sem2\CSCI3280\Project\Tkinter-Designer\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1280x720")
window.configure(bg = "#F8DBDE")


canvas = Canvas(
    window,
    bg = "#F8DBDE",
    height = 720,
    width = 1280,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    480.0,
    720.0,
    fill="#CF7793",
    outline="")

canvas.create_rectangle(
    0.0,
    0.0,
    1280.0,
    100.0,
    fill="#671B61",
    outline="")

canvas.create_rectangle(
    480.0,
    620.0,
    1280.0,
    720.0,
    fill="#AC5180",
    outline="")

canvas.create_rectangle(
    0.0,
    620.0,
    480.0,
    720.0,
    fill="#893271",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=20.0,
    y=640.0,
    width=60.0,
    height=60.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=100.0,
    y=640.0,
    width=60.0,
    height=60.0
)

canvas.create_text(
    382.0,
    666.0,
    anchor="nw",
    text="00 : 00",
    fill="#FFFFFF",
    font=("Inter", 20 * -1)
)
window.resizable(False, False)
window.mainloop()
